### ISSUE TITLE
src/*.md files are copied incorrectly from repository

### ISSUE THREAD

**Issue by mfe5003** [drh/lcc#37]
The src/*.md files have some issue where all are cloned from the github repository incorrectly.
This manifests, when trying to compile dagcheck.c, with the error messages:

```
line 1: invalid character `%'
line 1: invalid character `{'
line 1: invalid character `\015'
line 2: invalid character `#'
line 2: syntax error
line 2: invalid character `\015'
line 3: syntax error
line 3: invalid character `;'
line 3: invalid character `\015'
line 4: invalid character `#'
...
```

This might be something related to me using WSL, but I was tipped off to the issue by this google groups post: [here](https://groups.google.com/forum/#!searchin/comp.compilers.lcc/dagcheck$20invalid$20character%7Csort:date/comp.compilers.lcc/LdPWZVb2SNA/ZwSLH_UCNCgJ).

Workaround is to download all the *.md files through the github "raw" web interface for each file.

**Comment by ksherlock** [comment]
lburg doesn't like CRLF line terminators.  Your `git config core.autocrlf` settings are converting the LF line terminators to CRLF.

**Comment by mfe5003** [comment]
Thanks, autocrlf is in fact true for me
