### ISSUE TITLE
Question regarding origin of cpp - the C preprocessor

### ISSUE THREAD

**Issue by dibyendumajumdar** [drh/lcc#38]
Hi David,

I was wondering if you could share the history of the cpp C preprocessor. Was this written specifically for lcc?

Thanks and Regards
Dibyendu

**Comment by dibyendumajumdar** [comment]
Thanks for catching the typo. I found this which probably answers the question:

https://groups.google.com/d/msg/comp.std.c/Xw5H8TlQ4W4/deq8iZ6exvUJ

**Comment by polluks** [comment]
@dibyendumajumdar you may close this issue.
